baseURL = "https://namberino.github.io/"
title = "Nam's Journal"
languageCode = 'en-us'
theme = "hello-friend-ng"

defaultContentLanguage = 'en'
#defaultContentLanguageInSubdir = true

copyright = "Copyright © 2024 - Nam Nguyen"

PygmentsCodeFences = true
PygmentsStyle = "onedark"

pagination.pagerSize  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.

[params]
    # dateform        = "Jan 27, 2024"
    # dateformShort   = "Jan 27"
    # dateformNum     = "2024-01-27"
    # dateformNumTime = "2024-01-27 10:02"

    # Show a global language switcher in the navigation bar
    enableGlobalLanguageMenu = false

    enableThemeToggle = true

    enableLanguageToggle = true

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = true

    # Metadata mostly used in document's head
    description = "Nam Nguyen's portfolio and blog about tech and engineering"
    keywords = "homepage, blog, tech, engineering, portfolio, cybersecurity, embedded systems, electronics"
    images = [""]

[permalinks]
  posts = "/posts/:year/:month/:title/"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[[params.social]]
  name = "email"
  url  = "mailto:namberinos@gmail.com"

[[params.social]]
  name = "github"
  url  = "https://github.com/namberino"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/nam-nguyen-binh"

[languages]
  [languages.en]
    languageName = "en"
    weight = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.en.params]
    #subtitle  = "A Journal by Nam"

    # Subtitle for home
    homeSubtitle = "A low-level systems guy with a passion for embedded systems and robotics"

    [[languages.en.menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    [[languages.en.menu.main]]
    identifier = "blog"
    name       = "Posts"
    url        = "posts/"

    [languages.en.params.logo]
      logoText = "nam$journal"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
  
  [languages.vi]
    languageName = "vi"
    weight = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.vi.params]
    #subtitle = "Nam's Journal"

    # Subtitle for home
    homeSubtitle = "Kĩ thuật hệ thống nhúng và hệ thống cấp thấp"

    [[languages.vi.menu.main]]
    identifier = "about"
    name       = "About me"
    url        = "about/"
    [[languages.vi.menu.main]]
    identifier = "blog"
    name       = "Bài đăng"
    url        = "posts/"
      
      [languages.vi.params.logo]
        logoText = "nam$journal"
        logoHomeLink = "/"
        # or
        #
        # path = "/img/your-example-logo.svg"
        # alt = "Your example logo alt text"

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1

#[markup]
#  [markup.highlight]
#    anchorLineNos = false
#    codeFences = true
#    guessSyntax = false
#    hl_Lines = ''
#    hl_inline = false
#    lineAnchors = ''
#    lineNoStart = 1
#    lineNos = false
#    lineNumbersInTable = true
#    noClasses = true
#    noHl = false
#    style = 'monokai'
#    tabWidth = 4
